version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: cecotaps_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cecotaps_backend
    ports:
      - '5434:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
